### ISSUE TITLE
i know this is not a good question but WHERE SHOULD I RUN "PYPIXELART" COMMAND

### ISSUE THREAD

**Issue by srini-pro** [douglascdev/pypixelart#11]
I know this is not a good question but WHERE SHOULD I RUN "PYPIXELART" COMMAND pls help

**Comment by douglascdev** [comment]
Hello, the way to access a terminal will depend on your OS so I'll assume you're a Windows user, let me know if you're not.
The installation commands are run on the command prompt, which you can access by pressing the Windows key + R, typing cmd, and hitting enter. You can then proceed to the installation:
```
pip install pypixelart
```
After installing you can run it from there too:
```
pypixelart
```
Or just type `pypixelart` after pressing Windows + R, which should open a command prompt by itself.

**Comment by srini-pro** [comment]
> Hello, the way to access a terminal will depend on your OS so I'll assume you're a Windows user, let me know if you're not. The installation commands are run on the command prompt, which you can access by pressing the Windows key + R, typing cmd, and hitting enter. You can then proceed to the installation:
> 
> ```
> pip install pypixelart
> ```
> 
> After installing you can run it from there too:
> 
> ```
> pypixelart
> ```
> 
> Or just type `pypixelart` after pressing Windows + R, which should open a command prompt by itself.

hasnt worked

**Comment by douglascdev** [comment]
I'll need more information to help you. What OS are you running? What did you try step-by-step to run the program? What error did you get? What version of Python are you using?

**Comment by Kristoffer-Hallam** [comment]
Ok, so I am a MacOS Catalina version 10.15.7 user.

I ran
`pip install pypixelart `

and then executed on terminal
`pypixelart`

and got to this window
![Screen Shot 2022-03-30 at 21 44 08](https://user-images.githubusercontent.com/15235685/160954411-17063483-4e0a-404a-b6ec-05f590ede53b.png)


What should I do from here? The pixels are not positioned within the screen...

**Comment by douglascdev** [comment]
@Kristoffer-Hallam thank you for reporting it. You got a prompt in the console for file path, width and height before that window came up, right? It seems you entered 500 and 500. Since you entered values that big, the drawing area overflows from the visible screen and you can't tell what's going on. I'll try to fix that soon, as I understand it's quite confusing for users.

The solution, for now, should be just to enter smaller values or zoom out by pressing `b` until the area is visible. The zoom also seems to not be working very well for big images, so I'll try to get that fixed as well for the next release.

**Comment by douglascdev** [comment]
@Kristoffer-Hallam I've added a more dynamic method to initialize the zoom value,  keeping the image visible on the screen with larger or smaller dimensions of images. The update is already up here on github and will be available on PyPI when the next version is released. Feel free to open another issue if you face any other issues.

@srini-pro you haven't responded in a while so I'll close the issue, but feel free to open another one if you're still seeking help.
